[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

# LSP
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
	let g:lsp_settings_server_dir = '~/.lspServers'
'''

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

# 日本語関連のあれこれ
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'tyru/eskk.vim'

[[plugins]]
repo = 'vim-jp/autofmt'
