" load dein.vim
if has("mac")
	let g:python3_host_prog = expand('/Library/Frameworks/Python.framework/Versions/3.8/bin/python3')
elseif has("unix")
	let g:python3_host_prog = expand('/usr/sbin/python')
endif

if &compatible
	set nocompatible	" Be iMproved
endif

let s:dein_dir = expand('~/.cache/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# 'dein.vim'
	if !isdirectory(s:dein_repo_dir)
		execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
	endif
	execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif

if dein#load_state(s:dein_dir)
	call dein#begin(s:dein_dir)

	let g:rc_dir	= expand("~/.config/nvim/")
	let s:toml	= g:rc_dir . '/dein.toml'
	let s:lazy_toml	= g:rc_dir . '/dein_lazy.toml'

	call dein#load_toml(s:toml,		{'lazy' : 0})
	call dein#load_toml(s:lazy_toml,	{'lazy' : 1})

	call dein#end()
	call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

if dein#check_install()
	call dein#install()
endif

" load vimrc files
set runtimepath^=~/dotfiles/neovim/
runtime! config/basic/*.vim
runtime! config/plugin/*.vim
